### ISSUE TITLE
Error Message

### ISSUE THREAD

**Issue by darias08** [brdtheo/rawg-app#12]
Hello!

I am testing out your app and I am getting an error message saying, "[Error: Request failed with status code 401] undefined". 

I was wondering if you may know how to resolve this issue. I have installed the npm and updated some dependencies.  Thank you and I look forward to hearing from you soon! 

Screenshot links of Error message console:

first half 
https://drive.google.com/file/d/1_INslSxyA71MTPbXMsSYRpkvhu--6rpI/view?usp=share_link

second half
https://drive.google.com/file/d/1byPpBVKdJak5GLAliHymIao2vGpU9YmD/view?usp=share_link

**Comment by brdtheo** [comment]
Hello,

Did you put your API key in your `.env` as `RAWG_KEY` ? Since it returns a 401 it's probably an API related issue :)
You can do a simple test by accessing `https://api.rawg.io/api/platforms?key=RAWG_API_KEY`, it should return data.
![image](https://user-images.githubusercontent.com/48206778/202391902-31fa81e3-0d06-467b-b415-078344be0545.png)
